import { TuiTableModule } from '@taiga-ui/addon-table';
import { TuiAutoFocusModule, TuiLetModule } from '@taiga-ui/cdk';
import {
  TuiAlertModule,
  TuiButtonModule,
  TuiDataListModule,
  TuiDialogModule,
  TuiHostedDropdownModule,
  TuiErrorModule,
  TuiExpandModule,
  TuiHintModule,
  TuiModeModule,
  TuiLabelModule,
  TuiLinkModule,
  TuiRootModule,
  TuiScrollbarModule,
  TuiSvgModule,
  TuiTextfieldControllerModule,
  TuiLoaderModule,
  TuiGroupModule,
  TuiDropdownModule,
} from '@taiga-ui/core';

import {
  TuiAvatarModule,
  TuiFieldErrorPipeModule,
  TuiFilterByInputPipeModule,
  TuiInputModule,
  TuiInputPasswordModule,
  TuiInputPhoneModule,
  TuiMultiSelectModule,
  TuiComboBoxModule,
  TuiTabsModule,
  TuiTextAreaModule,
  TuiLineClampModule,
  TuiTreeModule,
  TuiAccordionModule,
  TuiToggleModule,
  TuiDataListWrapperModule,
  TuiSelectModule,
  TuiInputDateModule,
  TuiInputTimeModule,
  TuiBadgeModule,
  TuiTagModule,
} from '@taiga-ui/kit';

export const UImodules = [
  TuiTableModule,
  TuiAlertModule,
  TuiButtonModule,
  TuiDataListModule,
  TuiDialogModule,
  TuiHostedDropdownModule,
  TuiErrorModule,
  TuiExpandModule,
  TuiHintModule,
  TuiModeModule,
  TuiLabelModule,
  TuiLinkModule,
  TuiRootModule,
  TuiScrollbarModule,
  TuiSvgModule,
  TuiTextfieldControllerModule,
  TuiLoaderModule,
  TuiGroupModule,
  TuiDropdownModule,
  TuiAvatarModule,
  TuiFieldErrorPipeModule,
  TuiFilterByInputPipeModule,
  TuiInputModule,
  TuiInputPasswordModule,
  TuiInputPhoneModule,
  TuiMultiSelectModule,
  TuiComboBoxModule,
  TuiTabsModule,
  TuiTextAreaModule,
  TuiLineClampModule,
  TuiTreeModule,
  TuiAccordionModule,
  TuiToggleModule,
  TuiDataListWrapperModule,
  TuiSelectModule,
  TuiInputDateModule,
  TuiInputTimeModule,
  TuiBadgeModule,
  TuiTagModule,
  TuiAutoFocusModule,
  TuiLetModule,
];
